development:
  adapter: postgresql
  database: pani_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: pani_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pani_production
  pool: 5
  timeout: 5000